[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    ". /opt/venv/bin/activate && playwright install-deps",
    ". /opt/venv/bin/activate && playwright install chromium --with-deps"
]

[start]
cmd = ". /opt/venv/bin/activate && python main.py"
